name = "Rose Pine Dawn"
appearance = "light"

[colors]
background = "#faf4ed"
editor_background = "#faf4ed"
gutter = "#f4ede8"
status_bar = "#fffaf3"
divider = "#dfdad9"
cursor = "#575279"
selection = "#dfdad980"
text = "#575279"
text_muted = "#797593"
text_dimmed = "#9893a5"
result = "#286983"
error = "#b4637a"

[syntax]
number = "#575279"
operator = "#797593"
keyword = "#286983"
function = "#d7827e"
variable = "#ea9d34"
variable_def = "#ea9d34"
unit = "#56949f"
currency = "#286983"
label = "#ea9d34"
comment = "#9893a5"
header = "#907aa9"
percent = "#b4637a"
string = "#ea9d34"
scale = "#d7827e"
