name = "Tokyo Night"
appearance = "dark"

[colors]
background = "#1a1b26"
editor_background = "#1a1b26"
gutter = "#16161e"
status_bar = "#16161e"
divider = "#3b4261"
cursor = "#c0caf5"
selection = "#28345780"
text = "#c0caf5"
text_muted = "#a9b1d6"
text_dimmed = "#565f89"
result = "#9ece6a"
error = "#db4b4b"

[syntax]
number = "#c0caf5"
operator = "#89ddff"
keyword = "#9d7cd8"
function = "#7aa2f7"
variable = "#e0af68"
variable_def = "#e0af68"
unit = "#73daca"
currency = "#9ece6a"
label = "#e0af68"
comment = "#565f89"
header = "#bb9af7"
percent = "#f7768e"
string = "#9ece6a"
scale = "#ff9e64"
