name = "Tokyo Night Day"
appearance = "light"

[colors]
background = "#e1e2e7"
editor_background = "#e1e2e7"
gutter = "#e9e9ec"
status_bar = "#e9e9ec"
divider = "#a8aecb"
cursor = "#3760bf"
selection = "#c4c8da80"
text = "#3760bf"
text_muted = "#6172b0"
text_dimmed = "#848cb5"
result = "#587539"
error = "#c64343"

[syntax]
number = "#3760bf"
operator = "#006a83"
keyword = "#7847bd"
function = "#2e7de9"
variable = "#8c6c3e"
variable_def = "#8c6c3e"
unit = "#387068"
currency = "#587539"
label = "#8c6c3e"
comment = "#848cb5"
header = "#9854f1"
percent = "#f52a65"
string = "#587539"
scale = "#b15c00"
