name = "Zed One Dark"
appearance = "dark"

[colors]
background = "#282c33"
editor_background = "#282c33"
gutter = "#21252b"
status_bar = "#21252b"
divider = "#3B4048"
cursor = "#c8ccd4"
selection = "#293b5b80"
text = "#c8ccd4"
text_muted = "#abb2bf"
text_dimmed = "#5d636f"
result = "#a1c181"
error = "#d07277"

[syntax]
number = "#c8ccd4"
operator = "#6eb4bf"
keyword = "#b477cf"
function = "#73ade9"
variable = "#dfc184"
variable_def = "#dfc184"
unit = "#6eb4bf"
currency = "#a1c181"
label = "#dfc184"
comment = "#5d636f"
header = "#b477cf"
percent = "#d07277"
string = "#a1c181"
scale = "#bf956a"
