name = "Zed One Light"
appearance = "light"

[colors]
background = "#fafafa"
editor_background = "#fafafa"
gutter = "#efefef"
status_bar = "#eaeaed"
divider = "#d9dcea"
cursor = "#383a41"
selection = "#d9dcea80"
text = "#383a41"
text_muted = "#696c77"
text_dimmed = "#a2a3a7"
result = "#649f57"
error = "#d36151"

[syntax]
number = "#383a41"
operator = "#3882b7"
keyword = "#a449ab"
function = "#5b79e3"
variable = "#ad6e25"
variable_def = "#ad6e25"
unit = "#3882b7"
currency = "#649f57"
label = "#ad6e25"
comment = "#a2a3a7"
header = "#a449ab"
percent = "#d36151"
string = "#649f57"
scale = "#d3604f"
